# Include the role in your playbook
- name: Install New Relic infrastructure and logs
  hosts: all
  roles:
    - role: newrelic.newrelic_install
  vars:
    targets:
      - infrastructure
      - logs
      # - apm-php
      # - apm-dotnet
      # See all available targets at: https://github.com/newrelic/ansible-install
  environment:
    NEW_RELIC_API_KEY: NRAK-B0JTNDXKQ30Y0JR8VQQV0NJBE00
    NEW_RELIC_ACCOUNT_ID: "3899519"
    NEW_RELIC_REGION: US
